### ISSUE TITLE
npm run deploy ends up in Error (claudia create) on Linux

### ISSUE THREAD

**Issue by mhuebner** [ysugimoto/aws-lambda-image#125]
aws is setup and configured. npm-debug.log contains the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@4.1.2
3 info using node@v7.7.3
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle aws-lambda-image@0.12.0~predeploy: aws-lambda-image@0.12.0
6 silly lifecycle aws-lambda-image@0.12.0~predeploy: no script for predeploy, continuing
7 info lifecycle aws-lambda-image@0.12.0~deploy: aws-lambda-image@0.12.0
8 verbose lifecycle aws-lambda-image@0.12.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle aws-lambda-image@0.12.0~deploy: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/root/aws-lambda-image/node_modules/.bin:/root/.local/bin:/root/.local/bin:/root/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle aws-lambda-image@0.12.0~deploy: CWD: /root/aws-lambda-image
11 silly lifecycle aws-lambda-image@0.12.0~deploy: Args: [ '-c',
11 silly lifecycle   'claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json' ]
12 silly lifecycle aws-lambda-image@0.12.0~deploy: Returned: code: 1  signal: null
13 info lifecycle aws-lambda-image@0.12.0~deploy: Failed to exec deploy script
14 verbose stack Error: aws-lambda-image@0.12.0 deploy: `claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aws-lambda-image@0.12.0
16 verbose cwd /root/aws-lambda-image
17 error Linux 4.9.12-moby
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
19 error node v7.7.3
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error aws-lambda-image@0.12.0 deploy: `claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json`
22 error Exit status 1
23 error Failed at the aws-lambda-image@0.12.0 deploy script 'claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aws-lambda-image package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aws-lambda-image
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aws-lambda-image
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mhuebner** [comment]
Sometimes I get the following error output:

"Source directory is the Node temp directory. Cowardly refusing to fill up disk with recursive copy."

see https://github.com/claudiajs/claudia/blob/v2.9.0/src/commands/create.js#L53

```
			if (source === os.tmpdir()) {
				return 'Source directory is the Node temp directory. Cowardly refusing to fill up disk with recursive copy.';
			}
```

Adding --source /my/aws-lambda-image-directory does not help to resolve.

**Comment by mhuebner** [comment]
Ok, seems to be a problem with os.tmpdir() - this method returns the current working dir if run via npm. A workaround is to set TMPDIR environment variable:

`    "deploy": "TMPDIR=/tmp claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory -- --policies policies/*.json",
`

**Comment by kdybicz** [comment]
Huh, this is really interesting case. Though I'm not sure, if we can merge that into our config, because of people using`npm` under Cygwin and also this being the `root` edge case. For sure it's worth checking if simple `export TMPDIR=/tmp` will work and keeping that workaround in docs or wiki.

Are you working here with Docker or is there any reason why you need to use `root` account?

**Comment by mhuebner** [comment]
Yes, I am using a docker container (build my own based on wheezy-slim, nvm, ...) to have a clean environment.

I think it would be a good idea to mention the `TMPDIR ` env var in the docs. export should work, too!

**Comment by lilltiger** [comment]
Also if you are running in a virtual environment /tmp is often mapped to a ram drive that uses the vm's memory. So if you are on an EC2 instance you might just have 1GB ram, and the deloy uses alot of memory and then it will create a zip that also eats memory because of it being on the ram-drive.
So insted of /tmp use another folder, and also set up a swap.

I had alot of issues with different failurs that I latter hunted down to the vm runing out of memory while deploying.
