### ISSUE TITLE
Seems to fail on larger files

### ISSUE THREAD

**Issue by MarquisT** [ysugimoto/aws-lambda-image#137]
I spent a few hours trying to figure out why this wasn't working. When I look at the Cloudwatch Logs I see the following:
10:23:59
START RequestId: 70d58a24-42c6-11e7-90af-21dc9972d1b8 Version: $LATEST

10:23:59
2017-05-27T10:23:59.974Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Parsing S3 event...

10:23:59
2017-05-27T10:23:59.986Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Downloading: original/fishing6.jpg

10:24:00
2017-05-27T10:24:00.186Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Reducing to: in-place

10:24:01
2017-05-27T10:24:01.407Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Uploading to: original/reduced_fishing6.jpg (707873 bytes)

10:24:01
2017-05-27T10:24:01.424Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Resizing to: ./resized/small

10:24:01
2017-05-27T10:24:01.441Z	70d58a24-42c6-11e7-90af-21dc9972d1b8	Error: read ECONNRESET at exports._errnoException (util.js:1018:11) at Pipe.onread (net.js:572:26)

10:24:01
END RequestId: 70d58a24-42c6-11e7-90af-21dc9972d1b8

I tried this hours but finally I tried with only very small jpg files and it works perfectly. Any idea why it won't handle anything except very small jpgs?

**Comment by ysugimoto** [comment]
Currently I don't know why process fails on larger files.

Could you try to set memory size in Lambda setting and run again?

**Comment by Lidofernandez** [comment]
Any solution for this issue? I'm having the same problem

**Comment by ysugimoto** [comment]
Hmm, can I try to process that image which you failed?
I guess that sum of processed image is larger than Lambda's memory setting, it might be failed.

**Comment by Lidofernandez** [comment]
Sure thanks for the help 
![luxury-handbags2](https://user-images.githubusercontent.com/14365535/27623947-1ae1765a-5bdf-11e7-8ec6-1a97764bc467.jpg)

![mademoiselle](https://user-images.githubusercontent.com/14365535/27623955-24308836-5bdf-11e7-8813-332731807d13.jpg)

**Comment by jshow** [comment]
we see this with a 5.4m image - it fails every time

```
10:35:10
2017-12-06T15:35:10.292Z	9a262872-da9a-11e7-b755-c5c05efb5207	Error: read ECONNRESET at exports._errnoException (util.js:1018:11) at Pipe.onread (net.js:568:26)
2017-12-06T15:35:10.292Z	9a262872-da9a-11e7-b755-c5c05efb5207	Error: read ECONNRESET
at exports._errnoException (util.js:1018:11)
at Pipe.onread (net.js:568:26)
```

it seems to process the first thumbnail, and fails on the 2nd

We have lambda setup to use 3008 MB, the maximum - can't see why a 5.4 mb would trigger a read exception..odd

**Comment by aaroncrawford** [comment]
Has anyone found a workaround for this?  I love the idea of Lambda resizing our images but the solution won't work if it chokes on 5mb files.

**Comment by stormcrow85** [comment]
I'm having the same problem, only very small jpg's (under 50kb) or so are uploading perfectly, larger images creates some smaller sizes (70x70, 120x120) and fails on subsequent size like 350x350

**Comment by nikunjazova** [comment]
Does this work for large size image? Any update about this? 843KB file is not able to convert... Same issue.

**Comment by stormcrow85** [comment]
@nikunjazova did you try increasing memory and timeout in your Lambda function? Worked for me

![image](https://user-images.githubusercontent.com/4579192/40847755-e733869e-65c5-11e8-82c6-1661bdcd9396.png)

**Comment by aaroncrawford** [comment]
Checking back on this - anyone found a working solution to large 5mb+ files?  I increased Lambda memory and increased timeout, but still getting no output on 5+.  Thanks for everything @ysugimoto.

**Comment by tekdreams** [comment]
Hi everyone,

Same as @aaroncrawford . 
I'm having the same issues. Anyone found a workaround? 

Thanks

**Comment by ndxsoftware** [comment]
I think switching the node runtime from 10 to 8 fixes this …

Jason

**Comment by tekdreams** [comment]
Thank you for your response @ndxsoftware 

I've already switched to node runtime 8 before my last post. 
It still doesn't work. 

Matthieu

**Comment by CorrieMacDonald** [comment]
AWS Lambda has a disk limit of 500mb. Where underlying image processors create temporary cache files (Imagemagick is the usual suspect, creating huge temporary files), this will fail. It may also fail if there are subsequent processes occurring in parallel occupying the same physical disk limitations.

Even when IM is invoked using buffered inputs and ouputs to a buffer, it still has tendencies to create large temporary files.
