### ISSUE TITLE
Claudia: InvalidClientTokenId: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by jshow** [ysugimoto/aws-lambda-image#145]
Any thoughts ? AWS CLI is setup, perhaps a role issue for the iAM account ?

Really looking forward to testing this 🐶 out, thanks!

```
$ node --version
v8.5.0
$ npm run test-config
...
Configuration check finished.
Your configuration is green!
$ npm run deploy
> aws-lambda-image@0.13.0 deploy /home/jodi/aws-lambda-image
> claudia create --profile $npm_package_config_profile --region $npm_package_config_region --version dev --handler index.handler --no-optional-dependencies --timeout $npm_package_config_timeout --memory $npm_package_config_memory --policies policies/*.json

initialising IAM role	iam.createRole	RoleName=aws-lambda-image-executor
{ InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/jodi/aws-lambda-image/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',
  time: 2017-09-19T18:57:27.973Z,
  requestId: '61b3a06b-9d6c-11e7-84d1-5343584a983d',
  statusCode: 403,
  retryable: false,
  retryDelay: 85.19811774639332 }
```

**Comment by jshow** [comment]
The iAM role, limited to API access has `IAMFullAccess` and `AdministratorAccess` (probably excessive)

**Comment by jshow** [comment]
ack, looks like my AWS CLI config isn't working, hold this open, brb
```
$ aws ec2 describe-instances
An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
```

**Comment by jshow** [comment]
fixed! was AWS credentials all f8cked up. thanks!

**Comment by agueroveraalvaro** [comment]
Yes with `aws configure` I fixed
