### ISSUE TITLE
NOT ABLE TO COMPRESS .PNG IMAGES

### ISSUE THREAD

**Issue by safal20** [ysugimoto/aws-lambda-image#29]
first time when i run the code with the event having key "any.png" it shows me error

2016-05-11T06:11:43.882Z	3bcedd16-173f-11e6-9ba0-156ea9cbe5f2	Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at Pipe.onread (net.js:544:26)

if i run the same code for the second time it give me error

2016-05-11T06:12:20.081Z	511c8244-173f-11e6-b69d-77060bb8b8e4	{"errorMessage":"Woops, image process failed: ImageMagick errError: Command failed: convert: Expected 8192 bytes; found 6194 bytes `-' @ warning/png.c/MagickPNGWarningHandler/1777.
convert: Read Exception `-' @ error/png.c/MagickPNGErrorHandler/1751.
convert: corrupt image `-' @ error/png.c/ReadPNGImage/3789.
convert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3046.
"}

please look into the matter.
and tell me how can i remove that error?

**Comment by safal20** [comment]
can u please tell me what to do in the above case?

**Comment by ysugimoto** [comment]
It seems ImageMagick's error message.
This package using ImageMagick that installed in Lambda, through the `imagemagick` npm package.

I'll check resizeing process, and imagemagick package. thanks.
