### ISSUE TITLE
How can i set image quality (mozjpeg)?

### ISSUE THREAD

**Issue by mriechel** [ysugimoto/aws-lambda-image#46]
If have tried to add "-quality 80" to the args array in libs/optimizers/Mozjpeg.js, but then i get the following errors: (cloudwatch log)

2016-07-19T08:37:27.282Z	da078f59-4d8b-11e6-bf3c-edbd1dbf43c6	Error: write EPIPE at Object.exports._errnoException (util.js:870:11) at exports._exceptionWithHostPort (util.js:893:20) at WriteWrap.afterWrite (net.js:763:14)

**Comment by mriechel** [comment]
This works:
this.args    = ["-quality", "85", "-optimize", "-progressive"];

**Comment by ysugimoto** [comment]
@mriechel Thanks, I'll configurable it.

**Comment by ysugimoto** [comment]
Here is the configurable. thanks!
https://github.com/ysugimoto/aws-lambda-image/commit/40d5cf5b8d1e21a9baf7731d4c967dcfc4ab6cd9
